language: python

cache: pip

python:
  - 3.6

install: make
script: make test
after_success: make cov

deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
      branch: master
      tag: true

  - provider: pypi
    user: $TEST_PYPI_USER
    password: $TEST_PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    server: https://test.pypi.org/legacy/
    on:
      branch: develop
      tag: true
