language: python

cache: pip

python:
  - 3.6

install: make install
script: make test
after_success: make cov

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
      tags: true
