language: python

cache: pip

python:
  - 3.6

install: make install
script: make test
after_success: make cov

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build

deploy:
  skip_cleanup: true
  provider: script
  script: poetry publish
  on:
    tags: true
