language: python

cache: pip

python:
  - 3.6

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - pip install pipenv
  - pipenv install --dev --skip-lock

script:
  pipenv run pytest --cov=python_starter_pack --cov-report=xml -v

after_success:
  pipenv run codecov

deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
      branch: master

  - provider: pypi
    user: $TEST_PYPI_USER
    password: $TEST_PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    server: https://test.pypi.org/legacy/
    on:
      branch: staging
