language: python

cache: pip

python:
  - 3.6

install: make dev-install
script: make dev-test-full
after_success: make dev-cov

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  provider: script
  script: poetry publish --build --username $PYPI_USER --password $PYPI_PASSWORD
  on:
    tags: true
