version: "3"

services:
    auditorium:
        image: docker.pkg.github.com/apiad/auditorium/auditorium:latest
        build: "."
        volumes:
            - "./:/code"
        ports:
            - "6789:6789"
