version: "3"

services:
  auditorium-tester:
    container_name: auditorium-tester-${PYTHON_VERSION}
    image: docker.pkg.github.com/apiad/auditorium/auditorium:${PYTHON_VERSION}
    build:
      context: "."
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    volumes:
      - "./:/code"
      - "~/.ssh/id_rsa:/root/.ssh/id_rsa"
    command: make dev-test-full
    network_mode: host
    environment:
      - "NOW_TOKEN=${NOW_TOKEN}"
