site_name: Auditorium
theme: readthedocs
nav:
    - Home: index.md
    - Quick Start: quickstart.md
    - Hosting: hosting.md
    - Important Considerations: consider.md
    - Contributing: contributing.md
    - History: history.md
