[tool.poetry]
name = "auditorium"
version = "0.6.1"
description = "A Python-powered slideshow maker with steroids."
authors = ["Alejandro Piad <alepiad@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
markdown = "^3.1.1"
fire = "^0.2.1"
sanic = "^19.9.0"
jinja2 = "^2.10.3"
pygments = "^2.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
